### ISSUE TITLE
Bundle support for Symfony 4

### ISSUE THREAD

**Issue by hanishsingla** [Happyr/LinkedInBundle#9]
Hi 
I wanted to know if there are any plans to update this bundle for Symfony 4. I can help if needed.
Thanks

**Comment by Nyholm** [comment]
Hey.

Please do. As far as I know, you only need to remove symfony/symfony and add the proper dependencies there.

**Comment by hanishsingla** [comment]
Please accept my first pull request. This one is to avoid deprecated errors in Symfony 3.

I will push fixes as new deprecation comes in.

**Comment by Nyholm** [comment]
This is fixed in master now. Im about to tag a new release.
